#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2018 IBM Corp.

set -eou pipefail

# TODO: Make this more flexible as required
# * List supported configurations
# * Allow selection of a supported configuration
./ubuntu/17.10/openbmc-bootstrap "$@"
